image: node:12.7-alpine
 pipelines:
  default:
    - step:
        name: build
        caches:
          - node_modules
        script:
          - npm install --build-from-resource
          - npm run build --prod

  branches:
    master:
      - step:
         name: deployment
         image: google/cloud-sdk:latest
         caches:
           - docker
         script:
           - echo ${KEY_FILE_AUTH} | base64 --decode --ignore-garbage > /tmp/gcloud-api.json
           - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
           - gcloud config set project PROJECT_ID
           - gcloud builds submit --tag eu.gcr.io/PROJECT_ID/SERVICE_NAME
           - gcloud beta run deploy  SERVICE_NAME --image eu.gcr.io/PROJECT_ID/SERVICEN_AME --platform managed --region europe-west1 --allow-unauthenticated --set-env-vars=NODE_ENV='production'

options:
docker: true

